server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: EXAM-DATA-SERVICE
        uri: lb://EXAM-DATA-SERVICE
        predicates:
          - Path=/departments/**
        filters: 
          - name: CircuitBraker
            args:
              name: EXAM-DATA-SERVICE  
              fallbackuri: forward:/examServiceFallBack
      - id: STUDENT-DATA-SERVICE
        uri: lb://STUDENT-DATA-SERVICE
        predicates:
          - Path=/employees/**
        filters: 
          - name: CircuitBraker
            args:
              name: STUDENT-DATA-SERVICE  
              fallbackuri: forward:/studentServiceFallBack       
 

hystrix:  
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000   
            
            
management:
  endpoints:
    web:
      exposure:
        include: "*"     
              
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:   
    hostname: localhost         